import React, { useCallback, useState } from 'react';
import { UploadCloud, FileJson, Loader2 } from 'lucide-react';
import { SpaceData } from '../types';

interface UploaderProps {
  onDataLoaded: (data: SpaceData[]) => void;
}

export function Uploader({ onDataLoaded }: UploaderProps) {
  const [isDragging, setIsDragging] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(true);
  }, []);

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
  }, []);

  const processFiles = async (files: FileList | File[]) => {
    setIsLoading(true);
    setError(null);
    
    const validFiles = Array.from(files).filter(f => f.type === 'application/json' || f.name.endsWith('.json'));
    
    if (validFiles.length === 0) {
      setError('Please upload valid JSON file(s) generated by the bookmarklet.');
      setIsLoading(false);
      return;
    }

    try {
      const parsedDataArray: SpaceData[] = await Promise.all(validFiles.map(file => {
        return new Promise<SpaceData>((resolve, reject) => {
          const reader = new FileReader();
          reader.onload = (e) => {
            try {
              const json = JSON.parse(e.target?.result as string);
              if (!json.threads || typeof json.timestamp !== 'string') {
                throw new Error('Invalid format: Missing required fields');
              }
              resolve(json as SpaceData);
            } catch (err) {
              reject(err);
            }
          };
          reader.onerror = () => reject(new Error('Error reading file.'));
          reader.readAsText(file);
        });
      }));

      setTimeout(() => {
        onDataLoaded(parsedDataArray);
        setIsLoading(false);
      }, 800);
    } catch (err) {
      setError('Failed to parse one or more files. Ensure they were exported by the extraction script.');
      setIsLoading(false);
    }
  };

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    
    if (e.dataTransfer.files && e.dataTransfer.files.length > 0) {
      processFiles(e.dataTransfer.files);
    }
  }, []);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      processFiles(e.target.files);
    }
  };

  return (
    <div className="bg-white dark:bg-[#09090b] border border-zinc-200 dark:border-[#27272a] rounded-2xl p-6 md:p-8">
      <div className="flex items-center gap-3 mb-6">
        <div className="bg-indigo-500/20 p-2 rounded-lg text-indigo-400">
          <UploadCloud className="w-5 h-5" />
        </div>
        <h2 className="text-xl font-semibold text-zinc-900 dark:text-[#e4e4e7]">Step 2: Process Data</h2>
      </div>

      <div 
        onDragOver={handleDragOver}
        onDragLeave={handleDragLeave}
        onDrop={handleDrop}
        className={`border-2 border-dashed rounded-xl p-10 flex flex-col items-center justify-center text-center transition-all duration-200 ${
          isDragging 
            ? 'border-indigo-500 bg-indigo-500/5' 
            : 'border-zinc-200 dark:border-[#27272a] bg-zinc-100 dark:bg-[#18181b] hover:border-zinc-300 dark:border-[#3f3f46]'
        }`}
      >
        <input 
          type="file" 
          accept=".json" 
          multiple
          className="hidden" 
          id="file-upload" 
          onChange={handleFileChange}
        />
        
        {isLoading ? (
          <div className="flex flex-col items-center text-indigo-400">
            <Loader2 className="w-10 h-10 animate-spin mb-4" />
            <p className="text-sm font-medium">Parsing Space Data...</p>
          </div>
        ) : (
          <>
            <div className="p-4 bg-zinc-200 dark:bg-[#27272a] rounded-full mb-4">
              <FileJson className="w-8 h-8 text-zinc-600 dark:text-[#a1a1aa]" />
            </div>
            <h3 className="text-zinc-900 dark:text-[#e4e4e7] font-medium mb-2">Upload your Extracted Space JSON(s)</h3>
            <p className="text-sm text-zinc-500 dark:text-[#71717a] mb-6 max-w-sm">
              Drag and drop the files you downloaded in Step 1, or click the button below to browse. You can select multiple files for batch export.
            </p>
            <label 
              htmlFor="file-upload"
              className="cursor-pointer bg-black dark:bg-white text-white dark:text-black hover:opacity-80 text-sm font-bold px-6 py-2 rounded-lg transition-all"
            >
              Select File(s)
            </label>
          </>
        )}
      </div>

      {error && (
        <div className="mt-4 p-4 bg-red-500/10 border border-red-500/20 rounded-lg text-red-400 text-sm">
          {error}
        </div>
      )}
    </div>
  );
}
